# https://github.com/BamPeers/rust-ci-github-actions-workflow

on:
  pull_request:
  push:
    branches:
      - main

name: Test with Code Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/
            ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Test
        run: cargo test --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-tarpaulin
      - name: Generate test result and coverage report
        run: cargo tarpaulin --ignore-tests -o Html -o Lcov --timeout 240 --engine llvm
      - uses: coverallsapp/github-action@v2
        with:
          file: lcov.info
